// <auto-generated />
namespace PrescriptionAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MedicationUpdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MedicationUpdated));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:PrescriptionCapstone/PrescriptionAPI/PrescriptionAPI/Migrations/201910161735131_init.Designer.cs
            get { return "201910161735131_init"; }
=======
            get { return "201910161724103_MedicationUpdated"; }
>>>>>>> ae479a252db1cdb5085a35e9da4127356d363042:PrescriptionCapstone/PrescriptionAPI/PrescriptionAPI/Migrations/201910161724103_MedicationUpdated.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
